server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/wangzhc/springcloud_config
          username: 
          password: 
          
encrypt:
  key: foo

#对指定key加密
#curl -X POST http://localhost:8080/encrypt -d wangzhc
#对指定密码解密
#curl -X POST http://localhost:8080/decrypt -d xxxxxxxxxxxxxxx