server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/wangzhc/springcloud_config
          username: 
          password: 
          
encrypt:
  key: foo