server:
  port: 8031
spring:
  application:
    name: microservice-hystrix-turbine
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
turbine:
  aggregator:
    clusterConfig: MICROSERVICE-CONSUMER-MOVIE-RIBBON-WITH-HYSTRIX2
  appConfig: microservice-consumer-movie-ribbon-with-hystrix2
#如要要监控的instance已经配置了webroot (server.context-path: /xxx),则必须同在再turebin端声明路径
turbine.instanceUrlSuffix.MICROSERVICE-CONSUMER-MOVIE-RIBBON-WITH-HYSTRIX2: /ribbon/hystrix.stream

logging: 
  level:
    root: INFO
    com.netflix.turbine.monitor: DEBUG