server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/wangzhc/springcloud_config
          username: 
          password: 
          
encrypt:
  keyStore:
    location: classpath:/server.jks
    password: letmein
    alias: mytestkey
    secret: changeme